# Generated by Django 3.2.7 on 2021-09-30 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('no_of_days', models.FloatField()),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('leave_type', models.CharField(choices=[('Full', 'Full'), ('First Half', 'First Half'), ('Second Half', 'Second Half')], default='Full', max_length=15)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('remarks', models.TextField()),
                ('approval_status', models.CharField(choices=[('Pending', 'Pending'), ('Yes', 'Yes'), ('No', 'No')], default='Pending', max_length=15)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leave_requests', to=settings.AUTH_USER_MODEL)),
                ('leave', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leave_requests', to='leave.leave')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeLeave',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('remaining_leave', models.FloatField(blank=True, null=True)),
                ('can_apply_leave', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to=settings.AUTH_USER_MODEL)),
                ('leave', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='leave.leave')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
