# Generated by Django 3.2.7 on 2021-09-30 13:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('leave_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leave_approval', to='leave.leaverequest')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
