# Generated by Django 3.2.7 on 2021-10-01 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0005_auto_20211001_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeleave',
            name='total_days',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
