# Generated by Django 3.2.7 on 2021-10-02 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0006_employeeleave_total_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='leave_type',
        ),
    ]
