# Generated by Django 3.2.7 on 2021-10-02 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0007_remove_leaverequest_leave_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeaveApproval',
        ),
    ]
