# Generated by Django 3.2.7 on 2021-09-30 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-id'], 'verbose_name': 'Employee'},
        ),
    ]
